# this is a placeholder for development.  for the production version, see config/rubber/common/resque.yml
environments:
  development: 'appa-bumpr.iawjnt.0001.use1.cache.amazonaws.com:6379'
  test: 'localhost:6379'
